<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="patients" nsURI="http://webminz.github.com/emf/example/patients"
    nsPrefix="patients">
   <eClassifiers xsi:type="ecore:EClass" name="JournalSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patients" upperBound="-1"
        eType="#//Patient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" eType="#//Bed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observations" upperBound="-1"
        eType="#//Observation" containment="true" eOpposite="#//Observation/ofPatient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ofPatient" lowerBound="1"
        eType="#//Patient" eOpposite="#//Patient/observations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordedAt" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atStationNo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedNo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
